### PR TITLE
Zeus node advanced usage - es and getting started alby hub-es

### PR DESCRIPTION
**Pull request by DobleDJ**
This PR adds two new documentations translated into Spanish, with the aim of making our knowledge base more accessible to Spanish speakers. The translations have been carefully done to maintain the accuracy and clarity of the original content.

Changes Made:
Documentation 1: getting-started-alby-hub-es.html
Documentation 2: zeus-node-advanced-usage-es.html

### CODE REVIEW

**Comment by Darth-Coin** [comment]
Ok this is good. Will review and approve later. 
Thanks

**Comment by Darth-Coin** [comment]
Very nice PR! Thanks for keeping the same format.
Please send me your LN address to send you some sats for your effort.

**Comment by DobleDJ** [comment]
I am honored with those words I tried to keep the styles according to their work in the repository. I found this repository thanks to the informative work of the Cuba BTC Community.
My LN wallet is->  yoandydoble@getalby.com
Greetings

**Comment by Darth-Coin** [comment]
OK sent. Thanks again!

**Pull request merged**
